### ISSUE TITLE
Navigation using back button cause extra requests

### ISSUE THREAD

**Issue by madmoizo** [Charca/astro-records#2]
1 - Open your devtool > Network tab
2 - Click on a link
3 - Use the back button
4 - Repeat 2 & 3 a few time to see the extra (same) requests, it's cumulative
![image](https://github.com/Charca/astro-records/assets/11896237/af4837fe-a02f-4c1f-b82e-d6af49d5696b)

**Comment by Charca** [comment]
Thank you for reporting the issue! I've just upgraded to Astro 3.0 which should have taken care of this issue :)
