### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by xscd** [Charca/astro-records#3]
hi

I use Firefox 117 on a Linux machine. view transitions fallback seems to not work. 

[Screencast from 2023-08-30 22-26-17.webm](https://github.com/Charca/astro-records/assets/46658470/7eccae65-ab5c-430c-94c5-a3d721a7be57)

**Comment by Charca** [comment]
Thank you for reporting the issue! I was using the `fallback="swap"` attribute which disabled the transitions in Firefox to prevent a bug with the experimental version.

I've just upgraded to Astro 3.0 and the issue is fixed.
