### ISSUE TITLE
Jitter while scrolling a website on iPad/iPhone

### ISSUE THREAD

**Issue by mrdc** [Charca/astro-records#5]
Hello,

I have severe jitter while scrolling `https://astro-records.pages.dev` on iPad/iPhone (iPadOS 16.7/iOS 16.7)
Looks like live demo should be updated to astro 3+.
Related issue: https://github.com/withastro/astro/issues/8250

**Comment by Charca** [comment]
Hi @mrdc. This demo is using Astro 3 already. Are you still seeing the jitter while scrolling on iOS? I just tested on my iPhone and it worked without issues.

**Comment by mrdc** [comment]
> Hi @mrdc. This demo is using Astro 3 already. Are you still seeing the jitter while scrolling on iOS? I just tested on my iPhone and it worked without issues.

Fixed now)
BTW it's still not butter smooth on iPad/iPhone compared to React.
